// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXbnRmildq6yhb0EZmtsQzZYkKDcybL8',
    appId: '1:1026616756177:web:8dcd3ca6a27b045fc702f0',
    messagingSenderId: '1026616756177',
    projectId: 'klontong-76eb1',
    authDomain: 'klontong-76eb1.firebaseapp.com',
    storageBucket: 'klontong-76eb1.firebasestorage.app',
    measurementId: 'G-VE1ZZQJHQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOMwPXOmjMubId9mdttakQh2qXkFIbPM',
    appId: '1:1026616756177:android:0a0869d413465537c702f0',
    messagingSenderId: '1026616756177',
    projectId: 'klontong-76eb1',
    storageBucket: 'klontong-76eb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXBgxl0KuhnxIKyA0xC2mhyMa-GJWx8m8',
    appId: '1:1026616756177:ios:cb728f498ba43017c702f0',
    messagingSenderId: '1026616756177',
    projectId: 'klontong-76eb1',
    storageBucket: 'klontong-76eb1.firebasestorage.app',
    iosBundleId: 'com.example.klontong',
  );
}
